pool:
  vmImage: 'VS2017-Win2016'

steps:
- script: |
   npm install
   npm test
   npm run pack 
  workingDirectory: Azure
  displayName: 'Install, test and package app'

- task: CopyFiles@2
  displayName: 'Copy function files to Build.BinariesDirectory'
  inputs:
    SourceFolder: Azure
    Contents: |
     **/*.json
     .funcpack/**/*
    TargetFolder: '$(Build.BinariesDirectory)'

- task: ArchiveFiles@2
  displayName: 'Zip Build.BinariesDirector'
  inputs:
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'

- task: CopyFiles@2
  displayName: 'Copy ARM template'
  inputs:
    SourceFolder: Azure
    Contents: 'function-arm*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
